### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by PBomermustekiin** [fluttercandies/flutter_photo_manager#1128]
### Version

3.1.0

### Platforms

Android

### Device Model

Pixel 6a emulator

### flutter info

```sh
[✓] Flutter (Channel master, 3.22.0-28.0.pre.3, on macOS 14.4.1 23E224 darwin-arm64, locale tr-TR)
    • Flutter version 3.22.0-28.0.pre.3 on channel master at /Users/omer/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d6c00cc2b (4 days ago), 2024-05-08 16:35:24 +0530
    • Engine revision 071014f31c
    • Dart version 3.5.0 (build 3.5.0-131.0.dev)
    • DevTools version 2.35.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/omer/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Ömer iPhone 14 Pro Max (mobile) • 00008120-001A25803487C01E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 124.0.6367.158

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### How to reproduce?

Its working on ios but when im testing in android, im getting this error in emulator.

### Logs

```sh
I/flutter (10070): Error getting albums: MissingPluginException(No implementation found for method requestPermissionExtend on channel com.fluttercandies/photo_manager)
I/flutter (10070): error caught by report services: Bad state: No element
I/flutter (10070): error: #0      ListBase.firstWhere (dart:collection/list.dart:132:5)
I/flutter (10070): #1      PhotoManagerController.getAlbumByName (package:photo_recovery_mobile/Core/Global/Controllers/photo_manager_controller.dart:213:19)
I/flutter (10070): #2      PhotoManagerController.getRecentPhotos (package:photo_recovery_mobile/Core/Global/Controllers/photo_manager_controller.dart:197:31)
I/flutter (10070): #3      PhotoManagerController.onInitFunction (package:photo_recovery_mobile/Core/Global/Controllers/photo_manager_controller.dart:371:13)
I/flutter (10070): <asynchronous suspension>
I/flutter (10070):
```

### Contact

omermustekiin@gmail.com

**Comment by AlexV525** [comment]
Please restart your debugging session.
