### ISSUE TITLE
[BUG] Fatal Exception: android.database.sqlite.SQLiteException: too many SQL variables (code 1): 

### ISSUE THREAD

**Issue by shofizone** [fluttercandies/flutter_photo_manager#518]
A Fatal Exception: android.database.sqlite.SQLiteException caught form crashlytics.

I couldn't reproduce that bug. Catch from firebase crashlytics. But this might caused by calling   `PhotoManager.editor.android.removeAllNoExistsAsset()`

**Flutter version** :  2.2.1 (Stable)

 - Device: Redmi Note 5 Pro
 - OS: Android 8.1.0
 -  [75% - Android 8]
 -  [25% -Android 9 ]
 - Version [ photo_manager: ^1.2.1]

**Log**

```
Fatal Exception: android.database.sqlite.SQLiteException: too many SQL variables (code 1): , while compiling: SELECT media_type, _data, _id FROM files WHERE _id in ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,<truncated: 1759 chars>
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.delete(ContentProviderProxy.java:547)
       at android.content.ContentResolver.delete(ContentResolver.java:1652)
       at top.kikt.imagescanner.core.utils.DBUtils.removeAllExistsAssets(DBUtils.java:610)
       at top.kikt.imagescanner.core.PhotoManager.removeAllExistsAssets(PhotoManager.java:246)
       at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$21.invoke(PhotoManagerPlugin.java:447)
       at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$21.invoke(PhotoManagerPlugin.java:32)
       at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(PhotoManagerPlugin.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by AlexV525** [comment]
How many devices has this issue exactly? I was wondering how can we test this since we cannot create an invalid asset ourselves.

**Comment by shofizone** [comment]
Fortunately, the count is very few. Because as soon as we have noticed `PhotoManager.editor.android.removeAllNoExistsAsset()` is causing that we have removed it. We were using it to clean up the leftover data, in case user deleted the video from the phones' gallery, then the photo manager shows it as a valid item.

**Comment by AlexV525** [comment]
Is this issue still reproduced recently? Or any further details you can share about it?
