### ISSUE TITLE
[BUG] PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)

### ISSUE THREAD

**Issue by yy1300326388** [fluttercandies/flutter_photo_manager#725]
**To Reproduce**

我无法复现这个错误，线上用户会少量的报告这个错误。
但是我在操作之前，已经调用过了权限检查

``` Dart
Permission permission;
    if (Platform.isAndroid) {
      permission = Permission.storage;
    } else {
      permission = Permission.photos;
    }
// 这里是权限检查
    if (!await PermissionUtils.handlePermission(context, permission)) {
      return;
    }
AssetEntity asset = xxx
asset.originFile;// 这行代码会出现错误
```

**Flutter version**
v2.5.3

**Smartphone (please complete the following information):**
 - Device: HUAWEI、等
 - OS: [Android 10,level 29]

**Log**

```bash
PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
2
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
3
<asynchronous suspension>
4
#2 PhotoManager._getFileWithId (package:photo_manager/src/manager.dart:211)
5
<asynchronous suspension>
```

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/8764899/157605069-9a20abe8-d992-40cb-90a1-9248455993de.png">

**Comment by AlexV525** [comment]
有没有移除 ACCESS_MEDIA_LOCATION？

**Comment by yy1300326388** [comment]
没有移除，也没有提前请求此权限，是否要请求一下？

**Comment by AlexV525** [comment]
可以移除，也可以请求。

**Comment by yy1300326388** [comment]
我们的应用不需要  Exif 元数据，所以我尝试移除下个版本继续观察

**Comment by yy1300326388** [comment]
已尝试移除，感谢 :clown_face:

**Comment by AlexV525** [comment]
补充一点，权限检查可以尝试用 `PhotoManager.requestPermissionExtend`。
