### ISSUE TITLE
[BUG][BUG]java.lang.Error: java.io.FileNotFoundException: /storage/emulated/0/Pictures/CAP6719366998447182908.jpg (1): open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by purgeyao** [fluttercandies/flutter_photo_manager#727]
**Describe the bug**

code
```
    final List<AssetEntity> assets = await AssetPicker.pickAssets(
      context,
      pickerConfig: AssetPickerConfig(
        maxAssets: CollectionUtils.isNotNull(images) ? 9 - images.length : 9,
        // selectedAssets: pictures,
        themeColor: Theme.of(context).primaryColor,
      ),
    );
```

java.lang.Error: java.io.FileNotFoundException: /storage/emulated/0/Pictures/CAP6719366998447182908.jpg (1): open failed: ENOENT (No such file or directory)

**Flutter version**
flutter 2.10.2
```
  wechat_assets_picker: ^7.0.5
  wechat_camera_picker: ^3.0.0
  photo_manager: ^2.0.1
```
 `compileSdkVersion 32`

android 10

**Log**

error
```
java.lang.Error: java.io.FileNotFoundException: /storage/emulated/0/Pictures/CAP6719366998447182908.jpg (1): open failed: ENOENT (No such file or directory)
E/AndroidRuntime(27669): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
E/AndroidRuntime(27669): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(27669): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(27669): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Pictures/CAP6719366998447182908.jpg (1): open failed: ENOENT (No such file or directory)
E/AndroidRuntime(27669): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/AndroidRuntime(27669): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
E/AndroidRuntime(27669): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
E/AndroidRuntime(27669): 	at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5289)
E/AndroidRuntime(27669): 	at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3952)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:250)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.access$convertCursorToAssetEntity(AndroidQDBUtils.kt:29)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryId$1$1.invoke(AndroidQDBUtils.kt:177)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryId$1$1.invoke(AndroidQDBUtils.kt:176)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.cursorWithRange(AndroidQDBUtils.kt:138)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetFromGalleryId(AndroidQDBUtils.kt:176)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.PhotoManager.getAssetList(PhotoManager.kt:70)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$2.invoke(PhotoManagerPlugin.kt:245)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$2.invoke(PhotoManagerPlugin.kt:239)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
E/AndroidRuntime(27669): 	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
E/AndroidRuntime(27669): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(27669): 	... 2 more
E/AndroidRuntime(27669): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(27669): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime(27669): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(27669): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/AndroidRuntime(27669): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(27669): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
E/AndroidRuntime(27669): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/AndroidRuntime(27669): 	... 19 more
I/Process (27669): Sending signal. PID: 27669 SIG: 9
```

**Comment by purgeyao** [comment]
@AlexV525 God can take a look at it

**Comment by AlexV525** [comment]
Can you override the dependency and verify if it's fixed?

```yaml
dependency_overrides:
  photo_manager:
    git:
      url: https://github.com/fluttercandies/flutter_photo_manager
      ref: '2721218'
```

**Comment by purgeyao** [comment]
```
Because flutter_demo depends on wechat_camera_picker ^3.0.1 which depends on photo_manager ^2.0.1, photo_manager from hosted is required.
So, because flutter_demo depends on photo_manager from git, version solving failed.
pub get failed (1; So, because flutter_demo depends on photo_manager from git, version solving failed.)
```

**Comment by AlexV525** [comment]
Do the exact same as I said.
