### ISSUE TITLE
[BUG]Some Android phones crash

### ISSUE THREAD

**Issue by iOSYoungSir** [fluttercandies/flutter_photo_manager#764]
**Describe the bug**
Some users' phones on Android 11 crashed when they selected a photo, while others crashed when they opened the photo picker. I looked at the log and said no permissions, but my permissions are enabled.

**To Reproduce**
There are two types of crashes:
1、Some phones are open photo picker crashed;
2、Some mobile phones are normal to open the photo selector, select a photo crashed;

**Flutter version**
Flutter 2.10.4
Dart 2.16.2

**Smartphone (please complete the following information):**
 - Device: HUAWEI 、XIAOMI
 - OS: HarmonyOS 2.0.0  MIUI 13.0.5

**Log**
Case one：

java.lang.Error: java.io.FileNotFoundException: /storage/emulated/999/Pictures/WeiXin/mmexport1b6c3b20e4327adfa53b1c59e2f5e2b9.jpeg: open failed: EACCES (Permission denied)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /storage/emulated/999/Pictures/WeiXin/mmexport1b6c3b20e4327adfa53b1c59e2f5e2b9.jpeg: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5289)
	at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3952)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:252)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.access$convertCursorToAssetEntity(AndroidQDBUtils.kt:29)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryId$1$1.invoke(AndroidQDBUtils.kt:179)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryId$1$1.invoke(AndroidQDBUtils.kt:178)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.cursorWithRange(AndroidQDBUtils.kt:140)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetFromGalleryId(AndroidQDBUtils.kt:178)
	at com.fluttercandies.photo_manager.core.PhotoManager.getAssetList(PhotoManager.kt:70)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$2.invoke(PhotoManagerPlugin.kt:245)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$2.invoke(PhotoManagerPlugin.kt:239)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	... 2 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8182)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 19 more

Case two：

java.lang.Error: java.io.FileNotFoundException: /storage/emulated/0/DCIM/qinbaobao/IMG_346747785_20220101_160414711.heic: open failed: EFAULT (Bad address)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/DCIM/qinbaobao/IMG_346747785_20220101_160414711.heic: open failed: EFAULT (Bad address)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5289)
	at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3952)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.convertCursorToAssetEntity(AndroidQDBUtils.kt:252)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.access$convertCursorToAssetEntity(AndroidQDBUtils.kt:29)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryIdRange$1$1.invoke(AndroidQDBUtils.kt:222)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils$getAssetFromGalleryIdRange$1$1.invoke(AndroidQDBUtils.kt:221)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.cursorWithRange(AndroidQDBUtils.kt:140)
	at com.fluttercandies.photo_manager.core.utils.AndroidQDBUtils.getAssetFromGalleryIdRange(AndroidQDBUtils.kt:221)
	at com.fluttercandies.photo_manager.core.PhotoManager.getAssetListWithRange(PhotoManager.kt:81)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke(PhotoManagerPlugin.kt:257)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$3.invoke(PhotoManagerPlugin.kt:250)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:46)
	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
	at com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	... 2 more
Caused by: android.system.ErrnoException: open failed: EFAULT (Bad address)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7960)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 19 more
```bash

```

**Comment by iOSYoungSir** [comment]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**Comment by iOSYoungSir** [comment]
Permissions are enabled

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**Comment by iOSYoungSir** [comment]
Permissions are enabled

     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

android:requestLegacyExternalStorage="true"

**Comment by iOSYoungSir** [comment]
I'm using this plugin "wechat_assets_picker: ^7.1.1", which is dependent on “photo_manager”

**Comment by AlexV525** [comment]
This is resolved by #755 three weeks ago. Upgrade to the latest version of the manager and validate again.
