### ISSUE TITLE
在flutter和原生安卓混编的项目中，使用录制视频点击确认按钮保存时候报SQLiteException

### ISSUE THREAD

**Issue by JohnsonCYS** [fluttercandies/flutter_photo_manager#825]
同一台设备，在纯flutter项目中，使用flutter_wechat_camera_picker框架可以正常拍摄录制视频                                                                        当进行flutter和原生项目混编的时候，使用flutter_wechat_camera_picker框架录制视频 点击保存的时候报错如下：   

 E/SQLiteLog: (1) table files has no column named relative_path
2022-09-15 17:49:04.541 3293-3312/? E/SQLiteDatabase: Error inserting _data=/storage/emulated/0/video/1663235344539.3gp parent=222554 _display_name=1663235344539.3gp format=12299 description= title=REC1019116926254118464.mp4 duration=2197 bucket_id=90835937 date_added=1663235344 datetaken=1663235344000 date_modified=1663235344 media_type=3 mime_type=video/mp4 storage_id=65537 width=480 relative_path= height=720 bucket_display_name=video
    android.database.sqlite.SQLiteException: table files has no column named relative_path (code 1): , while compiling: INSERT INTO files(_data,parent,_display_name,format,description,title,duration,bucket_id,date_added,datetaken,date_modified,media_type,mime_type,storage_id,width,relative_path,height,bucket_display_name) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1547)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1418)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2342)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:2662)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:1964)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:266)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:152)
        at android.os.Binder.execTransact(Binder.java:704)                                                                                                                   

我注意到flutter_wechat_camera_picker中使用到的photo_manager库，有关于Fix invalid RELATIVE_PATH obtains with cursors on Android Q-. (#810)的changelog，但是目前我已经使用到最新版本（对应的photo_manager: ^2.2.1）  
 wechat_assets_picker: ^8.0.2
 wechat_camera_picker: ^3.5.0+1
还是出现关于relative_path的报错，而且出现问题的设备是低于安卓Q的

**Comment by AlexV525** [comment]
提供可以复现的最小 demo。

**Comment by JohnsonCYS** [comment]
我在新建的纯flutter demo复现了这个问题，地址[git@github.com:JohnsonCYS/test_p.git](url)
demo复现视频：

https://user-images.githubusercontent.com/22021959/190543674-f10a7f83-0660-4025-8bb5-1f859cd27e80.mp4

可以看到拍摄照片点击确认后，正常返回上一个页面并打印获取到图片路径；但是拍摄视频的时候点击确认后没有返回，此时日志抛出了异常
通过flutter run -v获取到的日志是
[flutter_log.txt](https://github.com/fluttercandies/flutter_photo_manager/files/9580158/flutter_log.txt)
通过android studio控制台抓到的手机日志：
[android_studio_log.txt](https://github.com/fluttercandies/flutter_photo_manager/files/9580167/android_studio_log.txt)
其中有关于sql插入的报错：
E/SQLiteLog: (1) table files has no column named relative_path
2022-09-16 10:12:19.752 3293-25451/? E/SQLiteDatabase: Error inserting _data=/storage/emulated/0/video/1663294339748.3gp parent=222554 _display_name=1663294339748.3gp format=12299 description= title=REC5191471390747052615.mp4 duration=1813 bucket_id=90835937 date_added=1663294339 datetaken=1663294339000 date_modified=1663294339 media_type=3 mime_type=video/mp4 storage_id=65537 width=480 relative_path= height=720 bucket_display_name=video
    android.database.sqlite.SQLiteException: table files has no column named relative_path (code 1): , while compiling: INSERT INTO files(_data,parent,_display_name,format,description,title,duration,bucket_id,date_added,datetaken,date_modified,media_type,mime_type,storage_id,width,relative_path,height,bucket_display_name) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1547)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1418)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2342)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:2662)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:1964)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:266)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:152)
        at android.os.Binder.execTransact(Binder.java:704)

android studio只过滤当前应用的日志如下：
[android_studio_log_2.txt](https://github.com/fluttercandies/flutter_photo_manager/files/9580171/android_studio_log_2.txt)

PS:使用官网demo，在同台设备【MI 5X, Xiaomi, 27】上并没有出现这个问题，比较诡异😂
