### ISSUE TITLE
[BUG]saveImage failed on  the device Xiaomi note5 when first run app

### ISSUE THREAD

**Issue by clycheng2015** [fluttercandies/flutter_photo_manager#867]
when I first run  the flutter_wechat_assets_picker:7.2.0 example, I miss a bug! when I click confirm button on the camera priview page, i get nothing, the page go back to the camera page! and the picture can not be found on the album！if  I do run again, everything ok !  I can find the picture on the album!    the test device info is below!
![image](https://user-images.githubusercontent.com/12255222/202695973-c751ba62-35af-46c9-99d4-3df5e0197cb4.png)

What puzzles me is that the first installation is not good, and running it again can do this

**To Reproduce**
1. run flutter_wechat_assets_picker example，Multi->Pick from camera
2. Click on the Special button,into the camera preview page,
3. take picture and go to the picture preview,the click the confirm button,
4. then  picture preview go back,nothing show! and no picture to album.

**Expected behavior**
picture can be save to album!

**Flutter version**
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/sanyu/.fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sanyu/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

some permisson config as below
android:requestLegacyExternalStorage="true" 

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

What I find the problem is when  I  click confirm,  it use the PhotoManager.editor.saveImage method and return null! I do not thnow why! the Permission dialog was shown and granted the permission,but No effect！

**Comment by AlexV525** [comment]
Since you're using Flutter 2.10.x which is outdated, the issue becomes invalid. Use the latest version to verify again.

**Comment by shirne** [comment]
photo_manager example has same issue.

When first run example
Advanced usages->save media example->
click  
1. save Image with bytes
2. save Image with path
3. save video
```
I/manager_exampl( 8241): ProcessProfilingInfo new_methods=1359 is saved saved_to_disk=1 resolve_classes_delay=8000
W/manager_exampl( 8241): Accessing hidden method Landroid/content/ContextWrapper;->getDisplay()Landroid/view/Display; (light greylist, linking)
I/Timeline( 8241): Timeline: Activity_launch_request time:166466222 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui (has extras) }
I/Timeline( 8241): Timeline: Activity_launch_request time:166471193 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui (has extras) }
[PhotoManager 📣] 2022-11-18T20:04:28.013317 - {mediaType: 1, id: 1769091, type: insert, uri: content://media/external/images/media/1769091, platform: android, galleryId: -1617409521}
[PhotoManager 📣] 2022-11-18T20:04:28.024460 - saved asset: null
[PhotoManager 📣] 2022-11-18T20:04:30.343727 - write image to file success: File: '/storage/emulated/0/Android/data/com.fluttercandies.photo_manager_example/files/downloads/1668773070126.jpg'
[PhotoManager 📣] 2022-11-18T20:04:30.424135 - {mediaType: 1, id: 1769092, type: insert, uri: content://media/external/images/media/1769092, platform: android, galleryId: -1935827872}
[PhotoManager 📣] 2022-11-18T20:04:30.450259 - {mediaType: 1, id: 1769092, type: insert, uri: content://media/external/images/media/1769092, platform: android, galleryId: -1935827872}
[PhotoManager 📣] 2022-11-18T20:04:30.472659 - saved asset: AssetEntity(id: 1769092 , type: AssetType.image)
[PhotoManager 📣] 2022-11-18T20:04:34.374833 - file path = 3206572
V/MediaPlayer( 8241): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8241): cleanDrmObj: mDrmObj=null mDrmSessionId=null
[PhotoManager 📣] 2022-11-18T20:04:34.494198 - {mediaType: 3, id: 1769093, type: insert, uri: content://media/external/video/media/1769093, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T20:04:34.516008 - {mediaType: 3, id: 1769093, type: insert, uri: content://media/external/video/media/1769093, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T20:04:34.520544 - saved asset: null
```

stop debug and run again
```
I/manager_exampl( 8671): ProcessProfilingInfo new_methods=965 is saved saved_to_disk=1 resolve_classes_delay=8000
[PhotoManager 📣] 2022-11-18T20:07:36.684155 - {mediaType: 1, id: 1769094, type: insert, uri: content://media/external/images/media/1769094, platform: android, galleryId: -1617409521}
[PhotoManager 📣] 2022-11-18T20:07:36.702583 - saved asset: AssetEntity(id: 1769094 , type: AssetType.image)
[PhotoManager 📣] 2022-11-18T20:07:39.258174 - write image to file success: File: '/storage/emulated/0/Android/data/com.fluttercandies.photo_manager_example/files/downloads/1668773259060.jpg'
[PhotoManager 📣] 2022-11-18T20:07:39.375177 - {mediaType: 1, id: 1769095, type: insert, uri: content://media/external/images/media/1769095, platform: android, galleryId: -1935827872}
[PhotoManager 📣] 2022-11-18T20:07:39.407605 - {mediaType: 1, id: 1769095, type: insert, uri: content://media/external/images/media/1769095, platform: android, galleryId: -1935827872}
[PhotoManager 📣] 2022-11-18T20:07:39.415329 - saved asset: AssetEntity(id: 1769095 , type: AssetType.image)
[PhotoManager 📣] 2022-11-18T20:07:42.751059 - file path = 3206572
V/MediaPlayer( 8671): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8671): cleanDrmObj: mDrmObj=null mDrmSessionId=null
[PhotoManager 📣] 2022-11-18T20:07:42.878789 - {mediaType: 3, id: 1769096, type: insert, uri: content://media/external/video/media/1769096, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T20:07:42.913173 - {mediaType: 3, id: 1769096, type: insert, uri: content://media/external/video/media/1769096, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T20:07:42.978350 - {mediaType: 3, id: 1769096, type: insert, uri: content://media/external/video/media/1769096, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T20:07:42.985887 - saved asset: AssetEntity(id: 1769096 , type: AssetType.video)
```

Flutter: stable 3.3.8
photo_manager: master

device:
![微信图片_20221118200918](https://user-images.githubusercontent.com/2263157/202702132-186229c3-383e-44b5-96ef-2ed5d3b3bef1.jpg)

**Comment by AlexV525** [comment]
Didn't reproduce with OnePlus 3 (Android 8.1). The issue seems to be device-specific.

```
[PhotoManager 📣] 2022-11-18T21:32:53.650402 - {mediaType: 1, id: 528077, type: insert, uri: content://media/external/images/media/528077, platform: android, galleryId: -1617409521}
[PhotoManager 📣] 2022-11-18T21:32:53.700309 - saved asset: AssetEntity(id: 528077 , type: AssetType.image)
[PhotoManager 📣] 2022-11-18T21:32:54.105568 - {mediaType: 1, type: delete, uri: content://media/external, platform: android}
[PhotoManager 📣] 2022-11-18T21:32:54.106747 - {mediaType: 3, type: delete, uri: content://media/external, platform: android}
[PhotoManager 📣] 2022-11-18T21:32:54.109036 - {mediaType: 2, type: delete, uri: content://media/external, platform: android}
[PhotoManager 📣] 2022-11-18T21:32:59.723194 - write image to file success: File: '/storage/emulated/0/Android/data/com.fluttercandies.photo_manager_example/files/downloads/1668778379432.jpg'
[PhotoManager 📣] 2022-11-18T21:32:59.840289 - {mediaType: 1, id: 528081, type: insert, uri: content://media/external/images/media/528081, platform: android, galleryId: -1935827872}
[PhotoManager 📣] 2022-11-18T21:32:59.857995 - {mediaType: 1, id: 528081, type: insert, uri: content://media/external/images/media/528081, platform: android, galleryId: -1935827872}
[PhotoManager 📣] 2022-11-18T21:32:59.861930 - saved asset: AssetEntity(id: 528081 , type: AssetType.image)
[PhotoManager 📣] 2022-11-18T21:33:05.331913 - file path = 3206572
I/MediaPlayer( 7215): constructor
I/MediaPlayer( 7215): setDataSource:/data/user/0/com.fluttercandies.photo_manager_example/cache/1668778383663.mp4
I/MediaPlayer( 7215): stop
V/MediaPlayer( 7215): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 7215): cleanDrmObj: mDrmObj=null mDrmSessionId=null
[PhotoManager 📣] 2022-11-18T21:33:05.452442 - {mediaType: 3, id: 528082, type: insert, uri: content://media/external/video/media/528082, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T21:33:05.479887 - {mediaType: 3, id: 528082, type: insert, uri: content://media/external/video/media/528082, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T21:33:05.513960 - {mediaType: 3, id: 528082, type: insert, uri: content://media/external/video/media/528082, platform: android, galleryId: 90835937}
[PhotoManager 📣] 2022-11-18T21:33:05.523343 - saved asset: AssetEntity(id: 528082 , type: AssetType.video)
```

**Comment by AlexV525** [comment]
Please verify if the issue can be reproduced by Android Emulator (Android 9 API 28).

**Comment by shirne** [comment]
only on miui
caught exceptions
```
E/saveImage(16080): error//storage/emulated/0/Pictures/1668778992414.jpg (Permission denied)
W/System.err(16080): java.io.FileNotFoundException: /storage/emulated/0/Pictures/1668778992414.jpg (Permission denied)
W/System.err(16080): 	at java.io.FileOutputStream.open0(Native Method)
W/System.err(16080): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err(16080): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err(16080): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:119)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.utils.DBUtils.saveImage(DBUtils.kt:344)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.PhotoManager.saveImage(PhotoManager.kt:172)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$15.invoke(PhotoManagerPlugin.kt:388)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$15.invoke(PhotoManagerPlugin.kt:382)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:44)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.$r8$lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown Source:0)
W/System.err(16080): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion$$ExternalSyntheticLambda0.run(Unknown Source:2)
W/System.err(16080): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(16080): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(16080): 	at java.lang.Thread.run(Thread.java:764)
```

at 
```
cursor.use {
    if (it.moveToNext()) {
        val targetPath = it.getString(0)
        targetPath.checkDirs()
        val outputStream = FileOutputStream(targetPath)
        refreshInputStream()
        outputStream.use { os -> inputStream.use { iStream -> iStream.copyTo(os) } }
    }
}
```
