### ISSUE TITLE
[Bug report] [!] CocoaPods could not find compatible versions for pod "photo_manager":

### ISSUE THREAD

**Issue by apstone** [fluttercandies/flutter_photo_manager#920]
### Version

2.6.0

### Platforms

iOS

### Device Model

Any

### flutter info

```sh
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-arm64, locale en-US)
    • Flutter version 3.7.10 on channel stable at /Users/aaronstone/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (5 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/aaronstone/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.3 22E252 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

### How to reproduce?

Anytime I run `flutter run`. Regardless of attempting a `flutter clean` prior.

### Logs

```sh
[ +547 ms] Running pod install... (completed in 543ms)
[        ] CocoaPods' output:
           ↳
[   +1 ms]       Preparing

               Analyzing dependencies

               Inspecting targets to integrate
                 Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

               Fetching external sources
               -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
               -> Fetching podspec for `connectivity_plus` from
`Flutter/ephemeral/.symlinks/plugins/connectivity_plus/macos`
               -> Fetching podspec for `firebase_analytics` from
`Flutter/ephemeral/.symlinks/plugins/firebase_analytics/macos`
               firebase_analytics: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
               -> Fetching podspec for `firebase_core` from `Flutter/ephemeral/.symlinks/plugins/firebase_core/macos`
               firebase_core: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
               -> Fetching podspec for `firebase_crashlytics` from
`Flutter/ephemeral/.symlinks/plugins/firebase_crashlytics/macos`
               Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this
error is
               unexpected, try running flutterfire configure again.
               firebase_crashlytics: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
               -> Fetching podspec for `firebase_messaging` from
`Flutter/ephemeral/.symlinks/plugins/firebase_messaging/macos`
               firebase_messaging: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
               -> Fetching podspec for `flutter_secure_storage_macos` from
               `Flutter/ephemeral/.symlinks/plugins/flutter_secure_storage_macos/macos`
               -> Fetching podspec for `in_app_review` from `Flutter/ephemeral/.symlinks/plugins/in_app_review/macos`
               -> Fetching podspec for `package_info_plus_macos` from
               `Flutter/ephemeral/.symlinks/plugins/package_info_plus_macos/macos`
               -> Fetching podspec for `path_provider_foundation` from
               `Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/macos`
               -> Fetching podspec for `photo_manager` from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`
               -> Fetching podspec for `share_plus_macos` from `Flutter/ephemeral/.symlinks/plugins/share_plus_macos/macos`
               -> Fetching podspec for `sqflite` from `Flutter/ephemeral/.symlinks/plugins/sqflite/macos`
               -> Fetching podspec for `url_launcher_macos` from
`Flutter/ephemeral/.symlinks/plugins/url_launcher_macos/macos`

               Resolving dependencies of `Podfile`
                 CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed
in repo
                 update
                 CDN: trunk Relative path: all_pods_versions_d_d_6.txt exists! Returning local because checking is only
performed in
                 repo update
                 CDN: trunk Relative path: Specs/d/d/6/ReachabilitySwift/5.0.0/ReachabilitySwift.podspec.json exists!
Returning local
                 because checking is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only
performed in
                 repo update
                 CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local
because checking
                 is only performed in repo update
                 CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local
because checking
                 is only performed in repo update
                 CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local
because checking
                 is only performed in repo update
                 CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local
because checking
                 is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_c_0_4.txt exists! Returning local because checking is only
performed in
                 repo update
                 CDN: trunk Relative path: Specs/c/0/4/Flutter/3.0.0/Flutter.podspec.json exists! Returning local because
checking is
                 only performed in repo update
               [!] CocoaPods could not find compatible versions for pod "photo_manager":
                 In Podfile:
                   photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)

               Specs satisfying the `photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)`
dependency were
               found, but they required a higher minimum deployment target.

               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in
               `raise_error_unless_state'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block
in
               unwind_for_conflict'
               <internal:kernel>:90:in `tap'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in
               `unwind_for_conflict'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in
               `attempt_to_activate'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in
               `process_topmost_state'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in
`resolve'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in
`resolve'

/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block
               in resolve_dependencies'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in
`section'

/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in
               `resolve_dependencies'

/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in
               `analyze'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in
`analyze'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block
in
               resolve_dependencies'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in
`section'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in
               `resolve_dependencies'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in
`install!'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in
`run'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
               /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

[+1895 ms] lib/main.dart:54:19: Error: Undefined name 'PConfigs'.
[        ]   PHttp.baseUrl = PConfigs.apiUrl[kReleaseMode]!;
[        ]                   ^^^^^^^^
[        ] lib/main.dart:94:18: Error: Undefined name 'PConfigs'.
[        ]   PSocket.create(PConfigs.wsUrl[kReleaseMode]!, authToken);
[        ]                  ^^^^^^^^
[+4875 ms] Exception: Error running pod install
[   +1 ms] "flutter run" took 10,990ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +58 ms] ensureAnalyticsSent: 57ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by apstone** [comment]
My Podfile specifies `platform :ios, '11.0'` - What should it be? I have tried `9.0`, `10.15`, `12.0`, `14.0`

**Comment by AlexV525** [comment]
> [!] CocoaPods could not find compatible versions for pod "photo_manager":
    In Podfile:
      photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)
    Specs satisfying the `photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)`
dependency were found, but they required a higher minimum deployment target.

**photo_manager/macos**

> [+1895 ms] lib/main.dart:54:19: Error: Undefined name 'PConfigs'.
[        ]   PHttp.baseUrl = PConfigs.apiUrl[kReleaseMode]!;
[        ]                   ^^^^^^^^
[        ] lib/main.dart:94:18: Error: Undefined name 'PConfigs'.
[        ]   PSocket.create(PConfigs.wsUrl[kReleaseMode]!, authToken);
[        ]                  ^^^^^^^^
[+4875 ms] Exception: Error running pod install
[   +1 ms] "flutter run" took 10,990ms.
[   +2 ms]

Pay attention to your own errors. We don't triage issues that are out of our scope.

**Comment by apstone** [comment]
@AlexV525 Regardless of that error in main, it still fails to install. See below:

```
flutter run
Running "flutter pub get" in mobile...
Resolving dependencies... (1.8s)
  async 2.10.0 (2.11.0 available)
  build_daemon 3.1.1 (4.0.0 available)
  build_runner 2.3.3 (2.4.1 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
  dio 4.0.6 (5.1.1 available)
  dio_smart_retry 1.4.0 (5.0.0 available)
  flutter_secure_storage 7.0.1 (8.0.0 available)
  flutter_secure_storage_macos 2.0.1 (3.0.0 available)
  flutter_secure_storage_windows 1.1.3 (2.0.0 available)
  flutter_svg 1.1.6 (2.0.4 available)
  image 3.3.0 (4.0.15 available)
  intl 0.17.0 (0.18.0 available)
  js 0.6.5 (0.6.7 available)
  matcher 0.12.13 (0.12.15 available)
  material_color_utilities 0.2.0 (0.3.0 available)
  meta 1.8.0 (1.9.1 available)
  package_info_plus 1.4.3+1 (3.0.3 available)
  package_info_plus_linux 1.0.5 (2.0.0 available)
  package_info_plus_macos 1.3.0 (2.0.0 available)
  package_info_plus_platform_interface 1.0.2 (2.0.1 available)
  package_info_plus_web 1.0.6 (2.0.0 available)
  package_info_plus_windows 2.1.0 (3.0.0 available)
  path 1.8.2 (1.8.3 available)
  petitparser 5.1.0 (5.3.0 available)
  qr 2.1.0 (3.0.1 available)
  share_plus 4.5.3 (6.3.1 available)
  share_plus_windows 3.0.1 (4.0.0 available)
  source_span 1.9.1 (1.10.0 available)
  test_api 0.4.16 (0.5.1 available)
  webview_flutter 2.8.0 (4.0.7 available)
  webview_flutter_android 2.10.4 (3.4.5 available)
  webview_flutter_platform_interface 1.9.5 (2.1.0 available)
  webview_flutter_wkwebview 2.9.5 (3.2.4 available)
  win32 3.1.4 (4.1.2 available)
Got dependencies!
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             519ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `connectivity_plus` from `Flutter/ephemeral/.symlinks/plugins/connectivity_plus/macos`
    -> Fetching podspec for `firebase_analytics` from `Flutter/ephemeral/.symlinks/plugins/firebase_analytics/macos`
    firebase_analytics: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_core` from `Flutter/ephemeral/.symlinks/plugins/firebase_core/macos`
    firebase_core: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_crashlytics` from `Flutter/ephemeral/.symlinks/plugins/firebase_crashlytics/macos`
    Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is
    unexpected, try running flutterfire configure again.
    firebase_crashlytics: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_messaging` from `Flutter/ephemeral/.symlinks/plugins/firebase_messaging/macos`
    firebase_messaging: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_secure_storage_macos` from
    `Flutter/ephemeral/.symlinks/plugins/flutter_secure_storage_macos/macos`
    -> Fetching podspec for `in_app_review` from `Flutter/ephemeral/.symlinks/plugins/in_app_review/macos`
    -> Fetching podspec for `package_info_plus_macos` from
    `Flutter/ephemeral/.symlinks/plugins/package_info_plus_macos/macos`
    -> Fetching podspec for `path_provider_foundation` from
    `Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/macos`
    -> Fetching podspec for `photo_manager` from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`
    -> Fetching podspec for `share_plus_macos` from `Flutter/ephemeral/.symlinks/plugins/share_plus_macos/macos`
    -> Fetching podspec for `sqflite` from `Flutter/ephemeral/.symlinks/plugins/sqflite/macos`
    -> Fetching podspec for `url_launcher_macos` from `Flutter/ephemeral/.symlinks/plugins/url_launcher_macos/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo
      update
      CDN: trunk Relative path: all_pods_versions_d_d_6.txt exists! Returning local because checking is only performed in
      repo update
      CDN: trunk Relative path: Specs/d/d/6/ReachabilitySwift/5.0.0/ReachabilitySwift.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in
      repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/10.7.0/Firebase.podspec.json exists! Returning local because checking
      is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_0_4.txt exists! Returning local because checking is only performed in
      repo update
      CDN: trunk Relative path: Specs/c/0/4/Flutter/3.0.0/Flutter.podspec.json exists! Returning local because checking is
      only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "photo_manager":
      In Podfile:
        photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)

    Specs satisfying the `photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)` dependency were
    found, but they required a higher minimum deployment target.

    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in
    `raise_error_unless_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in
    unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in
    `unwind_for_conflict'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in
    `attempt_to_activate'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in
    `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block
    in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in
    `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in
    `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in
    resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in
    `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

Exception: Error running pod install
```

**Comment by AlexV525** [comment]
> Specs satisfying the `photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)` dependency were
    found, but they required a higher minimum deployment target.

Setting the target platform with iOS does not help with errors with **macos**.

**Comment by apstone** [comment]
> > Specs satisfying the `photo_manager (from `Flutter/ephemeral/.symlinks/plugins/photo_manager/macos`)` dependency were
> > found, but they required a higher minimum deployment target.
> 
> Setting the target platform with iOS does not help with errors with **macos**.

Apologies - I see now that this was because I did not have the simulator running, so it was trying to build for macos. 🤦 

Thank you

**Comment by newpanjing** [comment]
macOS Podfile config:

```
platform :osx, '11.0'
```

That should be no problem.
