### ISSUE TITLE
getAssetPathList method error

### ISSUE THREAD

**Issue by lgh001** [fluttercandies/flutter_photo_manager#929]
### Version

2.6.0

### Platforms

Android

### Device Model

OnePlus 11(Android 13)

### flutter info

```sh
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### How to reproduce?

call the method PhotoManagerPlugin.getThumbnail

### Logs

```sh
I/flutter (23371): PlatformException(The getAssetPathList method has an error: null cannot be cast to non-null type
I/flutter (23371): kotlin.Boolean, java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Boolean
I/flutter (23371): 	at com.fluttercandies.photo_manager.core.utils.ConvertUtils.convertToOption(ConvertUtils.kt:72)
I/flutter (23371): 	at com.fluttercandies.photo_manager.core.utils.ConvertUtils.getOptionFromType(ConvertUtils.kt:64)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.entity.filter.CommonFilterOption.<init>(CommonFilterOption.kt:11)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.utils.ConvertUtils.convertToFilterOptions(ConvertUtils.kt:104)
I/flutter (23371): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin.getOption(PhotoManagerPlugin.kt:506)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.PhotoManagerPlugin.handleMethodResult(PhotoManagerPlugin.kt:270)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.PhotoManagerPlugin.access$handleMethodResult(PhotoManagerPlugin.kt:27)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:248)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:246)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.runOnBackground$lambda-0(PhotoManagerPlugin.kt:44)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.PhotoManagerPlugin$Companion.lambda$bZa62ZrXsGssc32bPH4oVAuIci4(Unknown
I/flutter (23371): Source:0)
I/flutter (23371): 	at
I/flutter (23371): com.fluttercandies.photo_manager.core.-$$Lambda$PhotoManagerPlugin$Companion$bZa62ZrXsGssc32bPH4oVAuIci4.run(Unknown
I/flutter (23371): Source:2)
```

**Comment by CaiJingLong** [comment]
Please add example code

**Comment by CaiJingLong** [comment]
Thanks for report, but the problem seem only in main branch, not in release 2.6.0.
Can it be reproduced on 2.6.0?
